### ISSUE TITLE
[Request]: Rename DatMan

### ISSUE THREAD

**Issue by TheEvilSkeleton** [SjoerdB93/DatMan#1]
Per the README, DatMan is developed with GNOME in mind. As such, I assume a goal of this project is to comply with the GNOME HIG right?

If so, then I propose to change the name of this app to one that complies with the GNOME HIG. The [GNOME App Naming guidelines](https://developer.gnome.org/hig/guidelines/app-naming.html) suggests to not use word combinations or made up words.

I didn't think of a name yet, but I want to know if you're open for renaming the app.

**Comment by SjoerdB93** [comment]
Hey,

Yes I am definitely open to renaming DatMan to be more in line with the Gnome App Naming guidelines. The goal is to at least loosely following the Gnome HIG indeed, but remain pragmatic whenever needed.

I actually haven't read the link there yet, but I will read through it. If you have any suggestions, I am open to it!

**Comment by SjoerdB93** [comment]
One easy "solution" would just be to go for "Data Manipulator", in that case I'd even get away with keeping the same app ID DatMan that I have right now. (Would probably not need a Flarhub rename either)

But I'm open to other ideas.

**Comment by SjoerdB93** [comment]
I've created a new branch with the name "Data Manipulator", but I won't merge it just yet as I'm still open for suggestions of other naming ideas.

**Comment by SjoerdB93** [comment]
Data Manipulator is a bit long though, longer than what the Gnome HIG suggests.
Some other ideas I was thinking of:
- Grapher, but this one apparently already exists. Maybe something similar would work though
- Plotter
- Data plotter
- Plotify (altough it's kind of a made-up word, which is not recommended, also there apparently exists something with that name, but it's a completely unrelated service)

Perhaps something with a single word, based on a noun or verb would also be an option:
- Transform 
- Evolve
- Analytics 

It would be nice if it would be immediately clear from the app name what it does. Which is to plot data, visualize it, and it enables you to do transformations/operations/manipulations (whatever you want to call it) on it. Only late in the development process I also added the feature to be able to insert data from an equation, manipulate that, and then save that to text files. That too is kind of a core feature.

I'll be thinking about if a bit more before merging the new branch (which also has some other patches). I'm happy to hear any other suggestions as well. I'm always kinda bad with this kind of stuff :)

**Comment by SjoerdB93** [comment]
Yes, I was also kinda keen on Graphs. Especially as it's the most clean and short one while still being descriptive.

**Comment by TheEvilSkeleton** [comment]
Agreed

**Comment by SjoerdB93** [comment]
Thanks a lot for the input, then it's decided, the new name is Graphs! 
I've changed the metadata as well as the desktop entries to the new name.

I've opened a PR at Flathub as well to update it over there, so now buildbot should do a test-build. I'll double check that there are no left-overs from the previous name though before I merge that one. I've installed and run the latest build locally and it looks fine, but it's probably good to check later anyway.

**Comment by TheEvilSkeleton** [comment]
Just a reminder, the name of this repo is still DatMan, so you could change it to Graphs.

**Comment by SjoerdB93** [comment]
I was just thinking about that. 
I've changed the metadata here as well now to reflect the new repo name. (So that the "Submit an Issue" link still works).

At one point I may want to clean this up internally in the code as well, as I have a lot of references to Datman. But that's probably part of a future patch.
